name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

        #lint là sửa cú pháp
      - name: Lint
        run: npm run lint -- --max-warnings=0

        #tạm thời bỏ qua test(test đôi khi cần db và env thì phải khai báo
      - name: Test
        run: npm run test -- --passWithNoTests

      - name: Build
        run: npm run build
